routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/categories', [App\Http\Controllers\CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{id}', [App\Http\Controllers\CategoryController::class, 'detail'])->name('categories-detail');

Route::get('/books', [App\Http\Controllers\BookController::class, 'index'])->name('book');
Route::get('/about-us', [App\Http\Controllers\AboutUsController::class, 'index'])->name('aboutus');
Route::get('/contact-us', [App\Http\Controllers\ContactUsController::class, 'index'])->name('contactus');
Route::get('/details/{id}', [App\Http\Controllers\DetailController::class, 'index'])->name('detail');


Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');

Route::get('/dashboard/subyek', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'index'])->name('dashboard-subyek');
Route::get('/dashboard/subyek/create', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'create'])->name('dashboard-subyek-create');
Route::get('/dashboard/subyek/{id}', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'details'])->name('dashboard-subyek-details');

Route::get('/dashboard/books', [App\Http\Controllers\Admin\DashboardBooksController::class, 'index'])->name('dashboard-books');
Route::get('/dashboard/books/create', [App\Http\Controllers\Admin\DashboardBooksController::class, 'create'])->name('dashboard-books-create');
Route::get('/dashboard/books/{id}', [App\Http\Controllers\Admin\DashboardBooksController::class, 'details'])->name('dashboard-books-details');

Route::get('/dashboard/covers', [App\Http\Controllers\Admin\DashboardcoversController::class, 'index'])->name('dashboard-covers');
Route::get('/dashboard/covers/create', [App\Http\Controllers\Admin\DashboardcoversController::class, 'create'])->name('dashboard-covers-create');
Route::get('/dashboard/covers/{id}', [App\Http\Controllers\Admin\DashboardcoversController::class, 'details'])->name('dashboard-covers-details');

Route::prefix('admin')
    ->namespace('Admin')
    // ->middleware(['auth','admin'])
    ->group(function(){
        Route::get('/',[App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin-dashboard');
        Route::resource('subject','\App\Http\Controllers\Admin\SubjectController');
        Route::resource('books','\App\Http\Controllers\Admin\BooksController');
        Route::resource('covers','\App\Http\Controllers\Admin\CoversController');
        Route::resource('circulation','\App\Http\Controllers\Admin\CirculationsController');
    });

app/Models/Covers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Covers extends Model
{
        protected $fillable = [
        'foto_cover', 'books_id'
    ];

    protected $hidden = [

    ];

        public function books(){
        return $this->belongsTo(Books::class, 'books_id', 'id');
    }

}

app/Http/Controllers/Admin/CoversController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Books;
use App\Models\Covers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;

class CoversController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            $query = Covers::with(['books']);

            return Datatables::of($query)
                ->addColumn('action', function ($item) {
                    return '
                        <div class="btn-group">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle mr-1 mb-1" 
                                    type="button" id="action' .  $item->id . '"
                                        data-toggle="dropdown" 
                                        aria-haspopup="true"
                                        aria-expanded="false">
                                        Aksi
                                </button>
                                <div class="dropdown-menu" aria-labelledby="action' .  $item->id . '">
                                    <form action="' . route('covers.destroy', $item->id) . '" method="POST">
                                        ' . method_field('delete') . csrf_field() . '
                                        <button type="submit" class="dropdown-item text-danger">
                                            Hapus
                                        </button>
                                    </form>
                                </div>
                            </div>
                    </div>';
                })
                ->editColumn('foto_cover', function ($item) {
                    return $item->foto_cover ? '<img src="' . Storage::url($item->foto_cover) . '" style="max-height: 80px;"/>' : '';
                })
                ->rawColumns(['action','foto_cover'])
                ->make();
        }
         return view('pages.admin.covers.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
                $books = Books::all();
        
        return view('pages.admin.covers.create',[
            'books' => $books
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $data['foto_cover'] = $request->file('foto_cover')->store('assets/foto_cover', 'public');

        Covers::create($data);

        return redirect()->route('covers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Covers:: findOrFail($id);
        $item->delete();
        
        return redirect()->route('covers.index');
    }
}

resources/views/pages/admin/covers/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Dentist Homepage
@endsection

@section('content')
    <div class="section-content section-dashboard-home" data-aos="fade-up">
      <div class="container-fluid">
        <div class="dashboard-heading">
          <h2 class="dashboard-title">Covers</h2>
          <p class="dashboard-subtitle">Create New Covers!</p>
        </div>
        <div class="dashboard-content">
          <div class="row">
            <div class="col-md-12">
              @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                  @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                  @endforeach
                </ul>
              </div>
              @endif
              <div class="card">
                <div class="card-body">
                  <form
                    action="{{ route('covers.store') }}"
                    method="POST"
                    enctype="multipart/form-data"
                  >
                    @csrf
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label>Judul Buku</label>
                      <select name="books_id" class="form-control">
                        @foreach ($books as $book)
                          <option value="{{ $book->id }}">{{ $book->judul_buku }}</option>
                        @endforeach
                      </select>
                        </div>
                        <div class="form-group">
                          <label>Image Covers</label>
                          <input
                            type="file"
                            name="foto_cover"
                            class="form-control"
                            required
                          />
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col text-right">
                        <button type="submit" class="btn btn-success px-5">
                          Save Now
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>   
@endsection

resources/views/pages/admin/covers/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Dentist Homepage
@endsection

@section('content')

<div class="section-content section-dashboard-home" data-aos="fade-up">
      <div class="container-fluid">
        <div class="dashboard-heading">
          <h2 class="dashboard-title">Dashboard</h2>
          <p class="dashboard-subtitle">Look what you have made today!</p>
        </div>
        <div class="dashboard-content">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-body">
                  <a
                    href="{{ route('covers.create') }}"
                    class="btn btn-primary mb-3"
                  >
                    + Tambah Covers Baru
                  </a>
                  <div class="table-responsive">
                    <table
                      class="table table-hover scroll-horizontal-vertical w-100"
                      id="crudTable"
                    >
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Judul Buku</th>
                          <th>Foto Cover</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>
                      <tbody></tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   
@endsection

@push('addon-script')
    <script>
        // AJAX DataTable
        var datatable = $('#crudTable').DataTable({
            processing: true,
            serverSide: true,
            ordering: true,
            ajax: {
                url: '{!! url()->current() !!}',
            },
            columns: [
          {data: 'id', name :'id'},
          {data: 'books.judul_buku', name: 'books.judul_buku' },
          {data: 'foto_cover', name :'foto_cover'},
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                    width: '15%'
                },
            ]
        });
    </script>
@endpush