routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/categories', [App\Http\Controllers\CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{id}', [App\Http\Controllers\CategoryController::class, 'detail'])->name('categories-detail');

Route::get('/books', [App\Http\Controllers\BookController::class, 'index'])->name('book');
Route::get('/about-us', [App\Http\Controllers\AboutUsController::class, 'index'])->name('aboutus');
Route::get('/contact-us', [App\Http\Controllers\ContactUsController::class, 'index'])->name('contactus');
Route::get('/details/{id}', [App\Http\Controllers\DetailController::class, 'index'])->name('detail');


Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');

Route::get('/dashboard/subyek', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'index'])->name('dashboard-subyek');
Route::get('/dashboard/subyek/create', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'create'])->name('dashboard-subyek-create');
Route::get('/dashboard/subyek/{id}', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'details'])->name('dashboard-subyek-details');

Route::get('/dashboard/books', [App\Http\Controllers\Admin\DashboardBooksController::class, 'index'])->name('dashboard-books');
Route::get('/dashboard/books/create', [App\Http\Controllers\Admin\DashboardBooksController::class, 'create'])->name('dashboard-books-create');
Route::get('/dashboard/books/{id}', [App\Http\Controllers\Admin\DashboardBooksController::class, 'details'])->name('dashboard-books-details');

Route::get('/dashboard/covers', [App\Http\Controllers\Admin\DashboardcoversController::class, 'index'])->name('dashboard-covers');
Route::get('/dashboard/covers/create', [App\Http\Controllers\Admin\DashboardcoversController::class, 'create'])->name('dashboard-covers-create');
Route::get('/dashboard/covers/{id}', [App\Http\Controllers\Admin\DashboardcoversController::class, 'details'])->name('dashboard-covers-details');

Route::prefix('admin')
    ->namespace('Admin')
    // ->middleware(['auth','admin'])
    ->group(function(){
        Route::get('/',[App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin-dashboard');
        Route::resource('subject','\App\Http\Controllers\Admin\SubjectController');
        Route::resource('books','\App\Http\Controllers\Admin\BooksController');
        Route::resource('covers','\App\Http\Controllers\Admin\CoversController');
        Route::resource('circulation','\App\Http\Controllers\Admin\CirculationsController');
    });

app/Models/Circulation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Circulation extends Model
{
    protected $fillable = [
        'nim', 'nomor_induk', 'jenis_koleksi', 'tgl_pinjam', 'tgl_kembali_1'
        , 'tgl_kembali_2', 'sts_wajib', 'sts_wajib_kbl'
    ];

    protected $hidden = [

    ];

}

app/Http/Controllers/Admin/CirculationsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Circulation;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class CirculationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          if (request()->ajax()) {
            $query = Circulation::query();

            return DataTables::of($query)
                ->addColumn('action', function ($item) {
                    return '
                    <div class="btn-group">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle mr-1 mb-1" 
                                    type="button" id="action' .  $item->id . '"
                                        data-toggle="dropdown" 
                                        aria-haspopup="true"
                                        aria-expanded="false">
                                        Aksi
                                </button>
                                <div class="dropdown-menu" aria-labelledby="action' .  $item->id . '">
                                    <a class="dropdown-item" href="' . route('circulation.edit', $item->id) . '">
                                        Sunting
                                    </a>
                                    <form action="' . route('circulation.destroy', $item->id) . '" method="POST">
                                        ' . method_field('delete') . csrf_field() . '
                                        <button type="submit" class="dropdown-item text-danger">
                                            Hapus
                                        </button>
                                    </form>
                                </div>
                            </div>
                    </div>';
                })
                ->rawColumns(['action'])
                ->make();
        }
         return view('pages.admin.Circulations.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $Circulations = Circulation::all();
        
        return view('pages.admin.Circulations.create',[
            'Circulations' => $Circulations
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        Circulation::create($data);

        return redirect()->route('circulation.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Circulation::findOrFail($id);

        return view('pages.admin.Circulations.edit',[
            'item' =>$item
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        // $data['slug'] = Str::slug($request->title);

        $item = Circulation:: findOrFail($id);
        $item->update($data);

        return redirect()->route('circulation.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Circulation:: findOrFail($id);
        $item->delete();
        
        return redirect()->route('circulation.index');
    }
}

resources/views/pages/admin/Circulations/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Dentist Homepage
@endsection

@section('content')
        <div class="section-content section-dashboard-home" data-aos="fade-up">
            <div class="container-fluid">
                <div class="dashboard-heading">
                    <h2 class="dashboard-title">Peminjaman</h2>
                    <p class="dashboard-subtitle">Create New Peminjaman!</p>
                </div>
                <div class="dashboard-content">
                    <div class="row">
                        <div class="col-md-12">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                            <div class="card">
                                <div class="card-body">
                                    <form
                                        action="{{ route('circulation.store') }}"
                                        method="POST"
                                        enctype="multipart/form-data"
                                    >
                                        @csrf
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>NIM</label>
                                                    <input
                                                        type="text"
                                                        name="nim"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label>Nomor Induk</label>
                                                    <input
                                                        type="text"
                                                        name="nomor_induk"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label>Jenis Koleksi</label>
                                                    <input
                                                        type="text"
                                                        name="jenis_koleksi"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Tanggal Pinjam</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="tgl_pinjam"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Tanggal Kembali
                                                        1</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="tgl_kembali_1"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Tanggal Kembali
                                                        2</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="tgl_kembali_2"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label>Status Wajib</label>
                                                    <input
                                                        type="text"
                                                        name="sts_wajib"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Statys Wajib kbl</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="sts_wajib_kbl"
                                                        class="form-control"
                                                        required
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col text-right">
                                                <button
                                                    type="submit"
                                                    class="btn btn-success px-5"
                                                >
                                                    Save Now
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/pages/admin/Circulations/edit.blade.php
@extends('layouts.dashboard')

@section('title')
    Dentist Homepage
@endsection

@section('content')
        <div class="section-content section-dashboard-home" data-aos="fade-up">
            <div class="container-fluid">
                <div class="dashboard-heading">
                    <h2 class="dashboard-title">Peminjaman</h2>
                    <p class="dashboard-subtitle">Edit New Peminjaman!</p>
                </div>
                <div class="dashboard-content">
                    <div class="row">
                        <div class="col-md-12">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                            <div class="card">
                                <div class="card-body">
                                    <form
                                        action="{{ route('circulation.update', $item->id) }}"
                                        method="POST"
                                        enctype="multipart/form-data"
                                    >
                                        @method('PUT') @csrf
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>NIM</label>
                                                    <input
                                                        type="text"
                                                        name="nim"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->nim }}"
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label>Nomor Induk</label>
                                                    <input
                                                        type="text"
                                                        name="nomor_induk"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->nomor_induk }}"
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label>Jenis Koleksi</label>
                                                    <input
                                                        type="text"
                                                        name="jenis_koleksi"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->jenis_koleksi }}"
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Tanggal Pinjam</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="tgl_pinjam"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->tgl_pinjam }}"
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Tanggal Kembali
                                                        1</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="tgl_kembali_1"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->tgl_kembali_1 }}"
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Tanggal Kembali
                                                        2</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="tgl_kembali_2"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->tgl_kembali_2 }}"
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label>Status Wajib</label>
                                                    <input
                                                        type="text"
                                                        name="sts_wajib"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->sts_wajib }}"
                                                    />
                                                </div>
                                                <div class="form-group">
                                                    <label
                                                        >Statys Wajib kbl</label
                                                    >
                                                    <input
                                                        type="text"
                                                        name="sts_wajib_kbl"
                                                        class="form-control"
                                                        required
                                                        value="{{ $item->sts_wajib_kbl }}"
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col text-right">
                                                <button
                                                    type="submit"
                                                    class="btn btn-success px-5"
                                                >
                                                    Save Now
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/pages/admin/Circulations/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Dentist Homepage
@endsection

@section('content')

<div class="section-content section-dashboard-home" data-aos="fade-up">
      <div class="container-fluid">
        <div class="dashboard-heading">
          <h2 class="dashboard-title">Dashboard</h2>
          <p class="dashboard-subtitle">Look what you have made today!</p>
        </div>
        <div class="dashboard-content">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-body">
                  <a
                    href="{{ route('circulation.create') }}"
                    class="btn btn-primary mb-3"
                  >
                    + Tambah Peminjaman Baru
                  </a>
                  <div class="table-responsive">
                    <table
                      class="table table-hover scroll-horizontal-vertical w-100"
                      id="crudTable"
                    >
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>NIM</th>
                          <th>Nomor Induk</th>
                          <th>jenis Koleksi</th>
                          <th>Tgl Pinjam</th>
                          <th>Tgl Kembali 1</th>
                          <th>Tgl Kembali 2</th>
                          <th>Sts Wajib</th>
                          <th>Sts Wajib KBL</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>
                      <tbody></tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   
@endsection

@push('addon-script')
    <script>
        // AJAX DataTable
        var datatable = $('#crudTable').DataTable({
            processing: true,
            serverSide: true,
            ordering: true,
            ajax: {
                url: '{!! url()->current() !!}',
            },
            columns: [
          {data: 'id', name :'id'},
          {data: 'nim', name :'nim'},
          {data: 'nomor_induk', name :'nomor_induk'},
          {data: 'jenis_koleksi', name :'jenis_koleksi'},
          {data: 'tgl_pinjam', name :'tgl_pinjam'},
          {data: 'tgl_kembali_1', name :'tgl_kembali_1'},
          {data: 'tgl_kembali_2', name :'tgl_kembali_2'},
          {data: 'sts_wajib', name :'sts_wajib'},
          {data: 'sts_wajib_kbl', name :'sts_wajib_kbl'},

                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                    width: '15%'
                },
            ]
        });
    </script>
@endpush