routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/categories', [App\Http\Controllers\CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{id}', [App\Http\Controllers\CategoryController::class, 'detail'])->name('categories-detail');

Route::get('/books', [App\Http\Controllers\BookController::class, 'index'])->name('book');
Route::get('/about-us', [App\Http\Controllers\AboutUsController::class, 'index'])->name('aboutus');
Route::get('/contact-us', [App\Http\Controllers\ContactUsController::class, 'index'])->name('contactus');
Route::get('/details/{id}', [App\Http\Controllers\DetailController::class, 'index'])->name('detail');


Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');

Route::get('/dashboard/subyek', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'index'])->name('dashboard-subyek');
Route::get('/dashboard/subyek/create', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'create'])->name('dashboard-subyek-create');
Route::get('/dashboard/subyek/{id}', [App\Http\Controllers\Admin\DashboardSubyekController::class, 'details'])->name('dashboard-subyek-details');

Route::get('/dashboard/books', [App\Http\Controllers\Admin\DashboardBooksController::class, 'index'])->name('dashboard-books');
Route::get('/dashboard/books/create', [App\Http\Controllers\Admin\DashboardBooksController::class, 'create'])->name('dashboard-books-create');
Route::get('/dashboard/books/{id}', [App\Http\Controllers\Admin\DashboardBooksController::class, 'details'])->name('dashboard-books-details');

Route::get('/dashboard/covers', [App\Http\Controllers\Admin\DashboardcoversController::class, 'index'])->name('dashboard-covers');
Route::get('/dashboard/covers/create', [App\Http\Controllers\Admin\DashboardcoversController::class, 'create'])->name('dashboard-covers-create');
Route::get('/dashboard/covers/{id}', [App\Http\Controllers\Admin\DashboardcoversController::class, 'details'])->name('dashboard-covers-details');

Route::prefix('admin')
    ->namespace('Admin')
    // ->middleware(['auth','admin'])
    ->group(function(){
        Route::get('/',[App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin-dashboard');
        Route::resource('subject','\App\Http\Controllers\Admin\SubjectController');
        Route::resource('books','\App\Http\Controllers\Admin\BooksController');
        Route::resource('covers','\App\Http\Controllers\Admin\CoversController');
        Route::resource('circulation','\App\Http\Controllers\Admin\CirculationsController');
    });

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>@yield('title')</title>
   
    {{-- Style --}}
    @stack('prepend-style')
    @include('includes.style')
    @stack('addon-style')

  </head>

  <body>

    {{-- Navbar --}}
    @include('includes.navbar')

    {{-- Page Content --}}
    @yield('content')

    {{-- Footer --}}
    @include('includes.footer')

    {{-- Script --}}
    @stack('prepend-script')
    @include('includes.script')
    @stack('addon-script')
    
  </body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>@yield('title')</title>

    @stack('prepend-style')
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <link href="/style/main.css" rel="stylesheet" />
   <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.12.1/datatables.min.css"/>
    @stack('addon-style')
  </head>

  <body>
    <div class="page-dashboard">
      <div class="d-flex" id="wrapper" data-aos="fade-right">
        <!-- Sidebar -->
        <div class="border-right" id="sidebar-wrapper">
          <div class="sidebar-heading text-center">
            <img src="/images/TA-Logo.svg" alt="" class="my-4" />
          </div>
          <div class="list-group list-group-flush">
            <a
              href="{{ route('dashboard') }}"
              class="list-group-item list-group-item-action {{ (request()->is('dashboard*')) ? 'active' : '' }}"
              >Dashboard</a
            >
            <a
              href="{{ route('subject.index') }}"
              class="list-group-item list-group-item-action {{ (request()->is('admin/subject*')) ? 'active' : '' }}"
              >Subjects</a
            >
            <a
              href="{{ route('books.index') }}"
              class="list-group-item list-group-item-action {{ (request()->is('admin/books*')) ? 'active' : '' }}"
              >Books</a
            >
            <a
              href="{{ route('covers.index') }}"
              class="list-group-item list-group-item-action {{ (request()->is('admin/covers*')) ? 'active' : '' }}"
              >Covers</a
            >
            <a
              href="/dashboard-appoinment.html"
              class="list-group-item list-group-item-action"
              >Peminjaman</a
            >
            <a
              href="/dashboard-galleries.html"
              class="list-group-item list-group-item-action"
              >Pengembalian</a
            >
          </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
          <nav
            class="navbar navbar-store navbar-expand-lg navbar-light fixed-top"
            data-aos="fade-down"
          >
            <button
              class="btn btn-secondary d-md-none mr-auto mr-2"
              id="menu-toggle"
            >
              &laquo; Menu
            </button>

            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto d-none d-lg-flex">
                <li class="nav-item dropdown">
                  <a
                    class="nav-link"
                    href="#"
                    id="navbarDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    <img
                      src="/images/icon-user.png"
                      alt=""
                      class="rounded-circle mr-2 profile-picture"
                    />
                    Hi, Admin
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/index.html"
                      >Back to Home</a
                    >
                    <!-- <a class="dropdown-item" href="/dashboard-account.html"
                      >Settings</a
                    > -->
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/">Logout</a>
                  </div>
                </li>
              </ul>
              <!-- Mobile Menu -->
              <ul class="navbar-nav d-block d-lg-none mt-3">
                <li class="nav-item">
                  <a class="nav-link" href="#"> Hi, Admin </a>
                </li>
              </ul>
            </div>
          </nav>

        {{-- Content --}}
        @yield('content')

        <!-- /#page-content-wrapper -->
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    @stack('prepend-script')
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.12.1/datatables.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
    <!-- Menu Toggle Script -->
    <script>
      $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>
    @stack('addon-script')
    </body>
</html>